create extension if not exists "uuid-ossp";

create table if not exists users (
  id text primary key,
  email text unique not null,
  "ticketNumber" bigint generated by default as identity,
  name text,
  username text unique,
  "createdAt" timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists github_users (
  id uuid primary key default uuid_generate_v4(),
  "createdAt" timestamptz default timezone('utc'::text, now()) not null,
  "userData" jsonb not null
);

alter table users enable row level security;
alter table github_users enable row level security;

create index if not exists users_username_idx on users(username);
